# [unstable]
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core", "compiler_builtins"]
#
[build]
# # target = "x86_64-blog_os.json"
# # target = "aarch64-ruspiro.json"
# target = "aarch64-unknown-linux-gnu"
target = "aarch64-unknown-none-softfloat"
rustflags = ["-C", "link-arg=--script=kernel8.ld"]
# [target.aarch64-unknown-linux-gnu]
# # linker = "/usr/local/bin/aarch64-linux-gnu-gcc"
# # linker = "/usr/bin/aarch64-linux-gnu-ld"
# linker = "rust-ld"
#
# # [target.'cfg(target_os = "none")']
# # runner = "bootimage runner"
